Merge upstream changes from LineageOS (#708)
* NotificationLightSettings: Remove noop fields when LED can't pulse

Change-Id: I639b7fc385ffbc551ca3708d9f42db59662b6bee

* DataUsageUtils: Clean up based on code review

* Add missing header
* Extract DataUsageContract.UID + " = ? " into a string
* Simplify "0" string
* Use try-with-resource block to ensure cursor is closed

This commit is based on the post-merge feedback of Kamaljeet Maini,
Fabrice Di Meglio and Danny Baumann.

Change-Id: I774948ba119e3e4a2dd438e1ed1588bfb9fefae2

* telephony: Disable the SIM state change receiver

We've mistakenly reimplemented this functionality at the telephony
framework because we didn't realize it was here to begin with (and
neutralized by a QC commit).
Having the QC configuration in place makes _both_ come up, which
is annoying...
Since the f/o/t implementation (change
Iddaef47eefeab43ed99ca6f27f81dffd8dd08689) uses different visual
assets people are already used to, let's forcefully use that one
for now until we figure out which one we want to retain...

Change-Id: I1dfab99e475b2d5aa4574ecdb5d0d7ee6cf00191

* Settings: statusbar: Enable notification icon count by default

This used to be enabled by default in previous releases.

Change-Id: I2eedf7d6a7864e8c27f74493af5227b61f7d8f31

* Settings: Rebrand to LineageOS

Change-Id: I7326fd71621b398345d318c9c38dbc44433c732a

* DeviceInfoSettings: Launch normal PlatLogo for LA version

Since we've removed the Cid-esque PlatLogo as part of the
LineageOS rebrand, get rid of the extra code and simply
launch the AOSP PlatLogo when tapping on the LA version pref.

Change-Id: I2b70d4115d890771999b0b1b97c8a70495a75562

* SimSettings: avoid NPE

Don't assume getPhoneAccount doesn't return null just because you're passing a
non-null argument.

Avoids:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.telecom.PhoneAccount.getLabel()' on a null object reference
       at com.android.settings.sim.SimSettings.updateCallValues(SimSettings.java:299)
       at com.android.settings.sim.SimSettings.updateActivitesCategory(SimSettings.java:237)
       at com.android.settings.sim.SimSettings.updateAllOptions(SimSettings.java:222)
       at com.android.settings.sim.SimSettings.updateSubscriptions(SimSettings.java:217)
       at com.android.settings.sim.SimSettings.-wrap4(SimSettings.java)
       at com.android.settings.sim.SimSettings$1.onSubscriptionsChanged(SimSettings.java:175)
       at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$1.handleMessage(SubscriptionManager.java:397)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Change-Id: Ibdb5a978744a8f3e5dd916d08297a07d98aca5be

* Settings: Update button backlight brightness in real time

When adjusting the button backlight brightness using the seekbar,
the brightness did not update in real time, but only when the
RESET button is tapped.

With this change, the brightness is updated instantly.

Change-Id: Ib4db8b4759f2b756495dc3f9319b35cdb548d9e5

* DeviceInfo: Set is_lineage intent when launching PlatLogo

We use this to decide whether to launch the LineageOS PlatLogo.

Change-Id: I23dfc7b6aa6b8d96d45a757a4b44f2399e62196c

* ButtonBacklight: Preview timeout once user stops dragging

Change-Id: I0abebe1041b6ad42b10e7d24f76ea17046e64666

* Settings: Remove leftover conflicts

Conflicts proposed by this https://github.com/HridayHS/Resurrection_packages_apps_Settings/commit/d0bd5d3c0757a2b351ab04b6a4cdcb3dad0feaae commit,

- If I had 1$ for every conflict I left I would be rich af